@startuml
'https://plantuml.com/use-case-diagram

actor Player as p
actor Admin as a

usecase "RegisterTeam" as UC1
usecase "CreateTurnament" as UC2
usecase "ManageTurnament" as UC3
usecase "ManageGame" as UC4
usecase "ViewScoreboard" as UC5

UC2 --> p
p --> UC1
a --> UC2
UC2 --> UC3
UC3 --> UC4
a --> UC5
p --> UC5
UC1 --> UC3

@enduml